### ISSUE TITLE
NEON Chemistry Shiny App

### ISSUE THREAD

**Issue by njlyon0** [lter/lterwg-emergent-shiny#1]
## Summary

EMERGENT wants a shiny app to show some NEON chemistry data and make cool graphs. Two apps currently exist to do this but Jeff wants these apps optimized

## Starting Tasks

- [x] Check out two existing shiny apps
- [x] Refine each & combine into a single app
    - [x] Refine table app
    - [x] Refine graph app
    - [x] Combine into single app
- [x] Optimize for speed
- [x] Get feedback from Jeff
    - [ ] Implement feedback from Jeff
- [ ] Get feedback from full EMERGENT working group
    - [ ] Implement feedback from full WG
- [ ] Deploy

## Useful links

- [EMERGENT Shiny GH Repo](https://github.com/lter/lterwg-emergent-shiny)
- [EMERGENT GH Project](https://github.com/lter/lterwg-emergent-website/projects/1)

**Comment by njlyon0** [comment]
## Update - Table App Absorbed

Absorbed "app_table.R" into the "neon_app.R" script and (to some extent) optimized for speed

**Comment by njlyon0** [comment]
## Update - Graph App Absorbed, Combination App Refined & Optimized

Big update but I've accomplished the following:
- Refined graph app code
- Integrated with table app (see "neon_app.R") 
- Refined combination app to make it sleek and (relatively) human-readable
- Limited start-up computing needs so each operation is pretty fast
    - Previous apps did all processing on front end regardless of user inputs
    - User selections then modified what was *displayed* but all the computing was still done under the hood
    - This could be a contributing factor to Jeff's stated concerns about the speed of the app

## Next
- At 12/1 meeting with Jeff & Sci Comp team:
    - Discuss current progress
    - Identify (A) improvements / changes to existing app and (B) expansions to app
    - Make timeline for tasks identified in A & B above

**Comment by njlyon0** [comment]
## Jeff Feedback

- [ ] Add descriptive overview tab
    - [ ] Cannibalize NEON [soil data info page](https://www.neonscience.org/data-collection/soils)
    - [x] Include NEON logo
- [ ] Wrangling tweaks
    - [ ] Integrate direct acquisition of data from NEON into wrangling script
    - [ ] Explore [NEON's tutorial hub](https://www.neonscience.org/resources/learning-hub) for relevant acquisition tutorial
    - [x] Retain all `ncldClass` types without modification
    - [x] Maybe drop `NA`s / unknown if such a category exists?
- [x] Soil tab tweaks
    - [x] Switch to using raw `nlcdClass` instead of my synthetic `ncldClassSimple`
    - [x] Include all subclasses (see feedback in wrangling component)
- [ ] Create new pH tab
    - [ ] Identify abbreviation for pH column in data (no `pH` column found so must be listed by another name)
    - [ ] pH by Site
    - [x] Same habitat dropdown as in soil moisture tab
- [ ] Work on button for getting most recent data direct from NEON *in the app*
    - [ ] Would be in a new tab
    - [ ] Include warning about how long it takes (likely ~10sec at least)

**Comment by jeffreyblanchard** [comment]
NEON soils https://www.neonscience.org/data-collection/soils

**Comment by jeffreyblanchard** [comment]
NEON tutorials - https://www.neonscience.org/resources/learning-hub

**Comment by jeffreyblanchard** [comment]
- [ ] NEON soil chemistry shiny app
    - [ ] Upload to github R code for updating soil csv
    - [ ] Overview tab for shiny app
    - [ ] Go over Nick's recent updates
